package mr

import (
	"fmt"
	"strings"
)

func GenerateDescription(
	index int,
	total int,
	base string,
	branch string,
	commits []string,
) string {
	var b strings.Builder
	b.WriteString("## Stacked Merge Request\n\n")
	b.WriteString(fmt.Sprintf(
		"This is **part %d of %d** in a stacked review chain.\n\n",
		index,
		total,
	))
	b.WriteString("### Stack order\n\n")
	b.WriteString(fmt.Sprintf(
		"%s → **%s**\n\n",
		base,
		branch,
	))
	b.WriteString("### Commits included\n\n")

	for _, c := range commits {

		if len(c) > 7 {
			c = c[:7]
		}

		b.WriteString(fmt.Sprintf("- %s\n", c))
	}
	b.WriteString("\n")
	b.WriteString("### Review tips\n\n")
	b.WriteString("- Review commit by commit\n")
	b.WriteString("- Later PRs depend on this one\n")
	b.WriteString("- Merging order should follow stack order\n")
	b.WriteString("\n---\n")
	b.WriteString("Generated by **git-split**\n")
	return b.String()
}
